import Head from "next/head";
export default function Home() {
  return (
    <div>
      <Head>
        <title>My first next project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to nextjs</h1>
    </div>
  );
}
